<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>preview</LangVersion>
    <RootNamespace>LootingBots</RootNamespace>
    <AssemblyName>Skwizzy.LootingBots</AssemblyName>
    <Version>1.8.0</Version>
    <ReleaseOutputDir>..\Build\BepInEx\plugins\Skwizzy.LootingBots\</ReleaseOutputDir>
    <DebugType>portable</DebugType>
    <PathMap Condition="'$(Configuration)' == 'Release'">$(MSBuildProjectDirectory)=/src/</PathMap>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.43" IncludeAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.27.*-*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.*-*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.*-*" PrivateAssets="all" />
    <PackageReference Include="RoR2.BepInEx.Analyzers" Version="1.0.*-*" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CommonExtensions">
      <HintPath>..\References\CommonExtensions.dll</HintPath>
    </Reference>
    <Reference Include="DrakiaXYZ-BigBrain">
      <HintPath>..\References\DrakiaXYZ-BigBrain.dll</HintPath>
    </Reference>
    <Reference Include="Fika.Core">
      <HintPath>..\References\Fika.Core.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\References\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>..\References\spt-common.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>..\References\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\References\hollowed.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\References\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="ItemComponent.Types">
      <HintPath>..\References\ItemComponent.Types.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\References\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="DissonanceVoip">
      <HintPath>..\References\DissonanceVoip.dll</HintPath>
    </Reference>
  </ItemGroup>
  <!-- Build script for release build-->
  <Target Name="CleanUnwantedFiles" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <AllFiles Include="$(OutputPath)**\*" />
      <FilesToKeep Include="$(OutputPath)$(TargetFileName)" />
      <FilesToKeep Include="$(OutputPath)$(TargetName).pdb" />
    </ItemGroup>
    <ItemGroup>
      <FilesToDelete Include="@(AllFiles)" Exclude="@(FilesToKeep)" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" />
  </Target>
  <Target Name="CopyBuildOutput" AfterTargets="CleanUnwantedFiles" Condition="'$(Configuration)' == 'Release'">
    <MakeDir Directories="$(ReleaseOutputDir)" />
    <ItemGroup>
      <RemainingFiles Include="$(OutputPath)**\*" />
      <RemainingFiles Include="..\LICENSE" />
    </ItemGroup>
    <Copy
      SourceFiles="@(RemainingFiles)"
      DestinationFiles="@(RemainingFiles-&gt;'$(ReleaseOutputDir)%(RecursiveDir)%(Filename)%(Extension)')"
    />
  </Target>
</Project>
