<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.8.0</Version>
    <RootNamespace>LootingBots</RootNamespace>
    <AssemblyName>Skwizzy.LootingBots</AssemblyName>
    <ReleaseOutputDir>..\Build\SPT_Runtime\user\mods\Skwizzy.LootingBots\</ReleaseOutputDir>
    <DebugType>portable</DebugType>
    <PathMap Condition="'$(Configuration)' == 'Release'">$(MSBuildProjectDirectory)=/src/</PathMap>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SPTushonka.Common" Version="4.1.3" />
    <PackageReference Include="SPTushonka.DI" Version="4.1.3" />
    <PackageReference Include="SPTushonka.Server.Core" Version="4.1.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Config\config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <!-- Build script for release build-->
  <Target Name="CleanUnwantedFiles" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <UnwantedFiles Include="$(OutputPath)*.deps.json;$(OutputPath)*.runtimeconfig.*" />
    </ItemGroup>
    <Delete Files="@(UnwantedFiles)" />
  </Target>
  <Target Name="CopyBuildOutput" AfterTargets="CleanUnwantedFiles" Condition="'$(Configuration)' == 'Release'">
    <MakeDir Directories="$(ReleaseOutputDir)" />
    <ItemGroup>
      <RemainingFiles Include="$(OutputPath)**\*" />
      <RemainingFiles Include="..\LICENSE" />
    </ItemGroup>
    <Copy
      SourceFiles="@(RemainingFiles)"
      DestinationFiles="@(RemainingFiles-&gt;'$(ReleaseOutputDir)%(RecursiveDir)%(Filename)%(Extension)')"
    />
  </Target>
</Project>
